language: node_js
node_js:
  - 0.11
before_script:
  - cd sdk
  - npm install -d
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - export CHROME_BIN=/usr/bin/google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ls -l lib/webcomponentsjs/
branches:
    only:
        - web-apps-sdk-ui
